"""trust_fraud_prevention_tables_module_06

Revision ID: 54e04d937561
Revises: afe5f58698f3
Create Date: 2026-07-30 10:53:26.452169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e04d937561'
down_revision: Union[str, Sequence[str], None] = 'afe5f58698f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence_label IN ('low', 'medium', 'high')", name='ck_verification_records_confidence_label'),
    sa.CheckConstraint("subject_type IN ('certificate', 'submission', 'profile', 'resume')", name='ck_verification_records_subject_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_records_subject', 'verification_records', ['subject_type', 'subject_id'], unique=False)
    op.create_table('authenticity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authenticity_scores_candidate_time', 'authenticity_scores', ['candidate_id', 'computed_at'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='raised', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('raised', 'under_review', 'upheld', 'dismissed')", name='ck_fraud_flags_status'),
    sa.CheckConstraint("subject_type IN ('certificate', 'submission', 'profile', 'resume')", name='ck_fraud_flags_subject_type'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_flags_candidate', 'fraud_flags', ['candidate_id'], unique=False)
    op.create_index('idx_fraud_flags_status', 'fraud_flags', ['status'], unique=False)
    op.create_index('idx_fraud_flags_subject', 'fraud_flags', ['subject_type', 'subject_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fraud_flag_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('candidate_statement', sa.Text(), nullable=True),
    sa.Column('supporting_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['fraud_flag_id'], ['fraud_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disputes_flag', 'disputes', ['fraud_flag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_disputes_flag', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('idx_fraud_flags_subject', table_name='fraud_flags')
    op.drop_index('idx_fraud_flags_status', table_name='fraud_flags')
    op.drop_index('idx_fraud_flags_candidate', table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index('idx_authenticity_scores_candidate_time', table_name='authenticity_scores')
    op.drop_table('authenticity_scores')
    op.drop_index('idx_verification_records_subject', table_name='verification_records')
    op.drop_table('verification_records')
    # ### end Alembic commands ###
