"""resume portfolio builder tables

Revision ID: a76c622e4c08
Revises: 44fd41ed1de0
Create Date: 2026-07-29 15:47:54.059141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76c622e4c08'
down_revision: Union[str, Sequence[str], None] = '44fd41ed1de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('target_job_description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('fact_check_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('fact_check_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('resume','cover_letter')", name='ck_generated_documents_document_type'),
    sa.CheckConstraint("fact_check_status IN ('pending','passed','failed')", name='ck_generated_documents_fact_check_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_documents_candidate_time', 'generated_documents', ['candidate_id', 'generated_at'], unique=False)
    op.add_column('candidate_profiles', sa.Column('username', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('portfolio_published', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint('uq_candidate_profiles_username', 'candidate_profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_profiles_username', 'candidate_profiles', type_='unique')
    op.drop_column('candidate_profiles', 'portfolio_published')
    op.drop_column('candidate_profiles', 'username')
    op.drop_index('idx_generated_documents_candidate_time', table_name='generated_documents')
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
