"""hackathon pipeline tables (module 05)

Revision ID: afe5f58698f3
Revises: 9e9330bc11f0
Create Date: 2026-07-29 22:08:30.207891

Autogenerated against the live Neon DB, cleanly detecting exactly the 6 new tables (no
unrelated diff). No `judge_evaluations` table (SRS design, not the architecture doc's —
see `.agents/decisions.md`'s dated entry for this module for the doc-conflict
resolution). `hackathon_team_members` uses a surrogate `id` PK with nullable
`candidate_id` + `github_username`/`display_name` fallbacks (doc's literal composite PK
can't represent an unregistered roster member) — same additive pattern Module 03's
`contribution_reports.github_username` already established.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe5f58698f3'
down_revision: Union[str, Sequence[str], None] = '9e9330bc11f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_org_id', sa.UUID(), nullable=True),
    sa.Column('organizer_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_mode', sa.Text(), server_default='direct', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_mode IN ('manual_csv', 'webhook', 'direct')", name='ck_hackathons_ingestion_mode'),
    sa.CheckConstraint("status IN ('draft', 'active', 'judging', 'finalized')", name='ck_hackathons_status'),
    sa.ForeignKeyConstraint(['organizer_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recruiter_watchlists_recruiter', 'recruiter_watchlists', ['recruiter_id'], unique=False)
    op.create_table('hackathon_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('track', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hackathon_teams_hackathon', 'hackathon_teams', ['hackathon_id'], unique=False)
    op.create_table('hackathon_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'team_id', name='uq_hackathon_rankings_hackathon_team')
    )
    op.create_index('idx_hackathon_rankings_hackathon_rank', 'hackathon_rankings', ['hackathon_id', 'rank'], unique=False)
    op.create_table('hackathon_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.CheckConstraint("role IN ('lead','member')", name='ck_hackathon_team_members_role'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'candidate_id', name='uq_hackathon_team_members_team_candidate')
    )
    op.create_index('idx_hackathon_team_members_team', 'hackathon_team_members', ['team_id'], unique=False)
    op.create_table('hackathon_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('presentation_id', sa.UUID(), nullable=True),
    sa.Column('repo_analysis_submission_id', sa.UUID(), nullable=True),
    sa.Column('judge_score', sa.Float(), nullable=True),
    sa.Column('judge_rationale', sa.Text(), nullable=True),
    sa.Column('judge_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judge_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.ForeignKeyConstraint(['repo_analysis_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', name='uq_hackathon_submissions_team')
    )
    op.create_index('idx_hackathon_submissions_team', 'hackathon_submissions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hackathon_submissions_team', table_name='hackathon_submissions')
    op.drop_table('hackathon_submissions')
    op.drop_index('idx_hackathon_team_members_team', table_name='hackathon_team_members')
    op.drop_table('hackathon_team_members')
    op.drop_index('idx_hackathon_rankings_hackathon_rank', table_name='hackathon_rankings')
    op.drop_table('hackathon_rankings')
    op.drop_index('idx_hackathon_teams_hackathon', table_name='hackathon_teams')
    op.drop_table('hackathon_teams')
    op.drop_index('idx_recruiter_watchlists_recruiter', table_name='recruiter_watchlists')
    op.drop_table('recruiter_watchlists')
    op.drop_table('hackathons')
    # ### end Alembic commands ###
