"""candidate intelligence tables

Revision ID: bfa4df0973c6
Revises: 14fb3de7e078
Create Date: 2026-07-29 14:15:37.102519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfa4df0973c6'
down_revision: Union[str, Sequence[str], None] = '14fb3de7e078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merged_conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('corroboration_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_id', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default='unverified', nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified','pending','verified','rejected')", name='ck_certifications_verification_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('repo_full_name', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('pr_count', sa.Integer(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('coding_ability', sa.Float(), nullable=True),
    sa.Column('project_quality', sa.Float(), nullable=True),
    sa.Column('leadership', sa.Float(), nullable=True),
    sa.Column('problem_solving', sa.Float(), nullable=True),
    sa.Column('innovation', sa.Float(), nullable=True),
    sa.Column('community_participation', sa.Float(), nullable=True),
    sa.Column('technical_consistency', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('renormalized_subscores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scores_candidate_time', 'talent_scores', ['candidate_id', 'computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scores_candidate_time', table_name='talent_scores')
    op.drop_table('talent_scores')
    op.drop_table('github_snapshots')
    op.drop_table('certifications')
    op.drop_table('badges')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
