"""ppt analyzer tables

Revision ID: e8a55dc975da
Revises: 44fd41ed1de0
Create Date: 2026-07-29 15:59:38.872893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a55dc975da'
down_revision: Union[str, Sequence[str], None] = '44fd41ed1de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('linked_repo', sa.Text(), nullable=True),
    sa.Column('hackathon_submission_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='processing', nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('processing','done','failed')", name='ck_presentations_status'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plagiarism_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('matched_presentation_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_presentation_id'], ['presentations.id'], ),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentation_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('innovation_score', sa.Float(), nullable=True),
    sa.Column('technical_feasibility_score', sa.Float(), nullable=True),
    sa.Column('presentation_quality_score', sa.Float(), nullable=True),
    sa.Column('business_potential_score', sa.Float(), nullable=True),
    sa.Column('overall_pitch_score', sa.Float(), nullable=True),
    sa.Column('renormalized_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_content_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_presentation_scores_presentation_time', 'presentation_scores', ['presentation_id', 'computed_at'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_image', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slides_presentation_index', 'slides', ['presentation_id', 'slide_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_slides_presentation_index', table_name='slides')
    op.drop_table('slides')
    op.drop_index('idx_presentation_scores_presentation_time', table_name='presentation_scores')
    op.drop_table('presentation_scores')
    op.drop_table('plagiarism_matches')
    op.drop_table('presentations')
    # ### end Alembic commands ###
