"""baseline schema

Revision ID: e8c387ea8123
Revises: 
Create Date: 2026-08-16 05:00:54.542488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c387ea8123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('input_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('langfuse_trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_subject', 'agent_runs', ['subject_type', 'subject_id'], unique=False)
    op.create_table('course_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IS NULL OR level IN ('beginner','intermediate','advanced')", name='ck_course_catalog_level'),
    sa.CheckConstraint("provider IN ('coursera','freecodecamp','vendor')", name='ck_course_catalog_provider'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_unprocessed_type', 'events', ['event_type'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_table('location_aliases',
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('canonical_name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('org_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("org_type IN ('company','university','hackathon_organizer')", name='ck_organizations_org_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_taxonomy',
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('synonyms', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('canonical_name')
    )
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence_label IN ('low', 'medium', 'high')", name='ck_verification_records_confidence_label'),
    sa.CheckConstraint("subject_type IN ('certificate', 'submission', 'profile', 'resume')", name='ck_verification_records_subject_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_records_subject', 'verification_records', ['subject_type', 'subject_id'], unique=False)
    op.create_table('fraud_detection_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('code_similarity_threshold', sa.Float(), server_default='0.75', nullable=False),
    sa.Column('text_similarity_threshold', sa.Float(), server_default='0.80', nullable=False),
    sa.Column('ocr_confidence_threshold', sa.Float(), server_default='0.55', nullable=False),
    sa.Column('photo_hash_max_distance', sa.Float(), server_default='4', nullable=False),
    sa.Column('ai_content_perplexity_threshold', sa.Float(), server_default='50', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code_similarity_threshold >= 0 AND code_similarity_threshold <= 1', name='ck_code_sim_range'),
    sa.CheckConstraint('ocr_confidence_threshold >= 0 AND ocr_confidence_threshold <= 1', name='ck_ocr_conf_range'),
    sa.CheckConstraint('text_similarity_threshold >= 0 AND text_similarity_threshold <= 1', name='ck_text_sim_range'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_detection_configs_org', 'fraud_detection_configs', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("role IN ('candidate','recruiter','organizer','judge','admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('leetcode_username', sa.Text(), nullable=True),
    sa.Column('github_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leetcode_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merged_conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hackathon_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('portfolio_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ingestion_status', sa.Text(), server_default='idle', nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('ingestion_stage', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('copilot_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copilot_conversations_recruiter_id', 'copilot_conversations', ['recruiter_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_owner_type_uploaded', 'files', ['owner_user_id', 'file_type', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_table('hackathons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_org_id', sa.UUID(), nullable=True),
    sa.Column('organizer_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_mode', sa.Text(), server_default='direct', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('ranking_status', sa.Text(), server_default='idle', nullable=False),
    sa.Column('ranking_error', sa.Text(), nullable=True),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_mode IN ('manual_csv', 'webhook', 'direct')", name='ck_hackathons_ingestion_mode'),
    sa.CheckConstraint("status IN ('draft', 'active', 'judging', 'finalized')", name='ck_hackathons_status'),
    sa.ForeignKeyConstraint(['organizer_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('role_title', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('scoring_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_definitions_created_by', 'interview_definitions', ['created_by_user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('posted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matching_status', sa.Text(), server_default='idle', nullable=False),
    sa.Column('matching_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_organization_id', 'jobs', ['organization_id'], unique=False)
    op.create_index('idx_jobs_posted_by_user_id', 'jobs', ['posted_by_user_id'], unique=False)
    op.create_table('recruiter_watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recruiter_watchlists_recruiter', 'recruiter_watchlists', ['recruiter_id'], unique=False)
    op.create_table('trusted_issuers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_url_template', sa.Text(), nullable=True),
    sa.Column('trust_tier', sa.Text(), server_default='platform', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trust_tier IN ('platform','university','employer','community')", name='ck_trusted_issuers_trust_tier'),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), server_default='sourced', nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IS NULL OR source IN ('direct','copilot_search','hackathon')", name='ck_applications_source'),
    sa.CheckConstraint("stage IN ('sourced', 'screened', 'interview_scheduled', 'offered', 'rejected', 'hired')", name='ck_applications_stage'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_applications_job_candidate')
    )
    op.create_index('idx_applications_candidate', 'applications', ['candidate_id'], unique=False)
    op.create_index('idx_applications_job_stage', 'applications', ['job_id', 'stage'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('coding','mcq','project_analysis')", name='ck_assessments_type'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_candidate', 'assessments', ['candidate_id'], unique=False)
    op.create_table('authenticity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authenticity_scores_candidate_time', 'authenticity_scores', ['candidate_id', 'computed_at'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('corroboration_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_badges_candidate', 'badges', ['candidate_id'], unique=False)
    op.create_table('career_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.Text(), nullable=True),
    sa.Column('skill_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_courses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_estimate_low', sa.Integer(), nullable=True),
    sa.Column('salary_estimate_high', sa.Integer(), nullable=True),
    sa.Column('salary_rationale', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_career_recs_candidate_time', 'career_recommendations', ['candidate_id', 'generated_at'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_id', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default='unverified', nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified','pending','verified','rejected')", name='ck_certifications_verification_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_certifications_candidate_id', 'certifications', ['candidate_id'], unique=False)
    op.create_table('contribution_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_full_name', sa.Text(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('contribution_share', sa.Float(), nullable=True),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('lines_survived', sa.Integer(), nullable=True),
    sa.Column('prs_opened', sa.Integer(), nullable=True),
    sa.Column('prs_reviewed', sa.Integer(), nullable=True),
    sa.Column('anomaly_note', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contribution_reports_candidate_id', 'contribution_reports', ['candidate_id'], unique=False)
    op.create_index('idx_contribution_reports_repo', 'contribution_reports', ['repo_full_name'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='raised', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('raised', 'under_review', 'upheld', 'dismissed')", name='ck_fraud_flags_status'),
    sa.CheckConstraint("subject_type IN ('certificate', 'submission', 'profile', 'resume')", name='ck_fraud_flags_subject_type'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_flags_candidate', 'fraud_flags', ['candidate_id'], unique=False)
    op.create_index('idx_fraud_flags_status', 'fraud_flags', ['status'], unique=False)
    op.create_index('idx_fraud_flags_subject', 'fraud_flags', ['subject_type', 'subject_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('target_job_description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('fact_check_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('fact_check_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('resume','cover_letter')", name='ck_generated_documents_document_type'),
    sa.CheckConstraint("fact_check_status IN ('pending','passed','failed')", name='ck_generated_documents_fact_check_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_documents_candidate_time', 'generated_documents', ['candidate_id', 'generated_at'], unique=False)
    op.create_table('github_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('repo_full_name', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('pr_count', sa.Integer(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_github_snapshots_candidate', 'github_snapshots', ['candidate_id'], unique=False)
    op.create_table('hackathon_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('track', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hackathon_teams_hackathon', 'hackathon_teams', ['hackathon_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('interview_definition_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='in_progress', nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','completed','abandoned')", name='ck_interview_sessions_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['interview_definition_id'], ['interview_definitions.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_sessions_candidate_id', 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index('idx_interview_sessions_definition', 'interview_sessions', ['interview_definition_id'], unique=False)
    op.create_index('idx_interview_sessions_job_id', 'interview_sessions', ['job_id'], unique=False)
    op.create_table('match_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=True),
    sa.Column('skill_similarity', sa.Float(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('experience_match', sa.Float(), nullable=True),
    sa.Column('talent_score_alignment', sa.Float(), nullable=True),
    sa.Column('project_relevance', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_match_scores_job_candidate')
    )
    op.create_index('idx_match_scores_candidate_id', 'match_scores', ['candidate_id'], unique=False)
    op.create_index('idx_match_scores_job_percentage', 'match_scores', ['job_id', 'match_percentage'], unique=False)
    op.create_index('idx_match_scores_job_time', 'match_scores', ['job_id', 'computed_at'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('linked_repo', sa.Text(), nullable=True),
    sa.Column('hackathon_submission_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='processing', nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('processing','done','failed')", name='ck_presentations_status'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('coding_ability', sa.Float(), nullable=True),
    sa.Column('project_quality', sa.Float(), nullable=True),
    sa.Column('leadership', sa.Float(), nullable=True),
    sa.Column('problem_solving', sa.Float(), nullable=True),
    sa.Column('innovation', sa.Float(), nullable=True),
    sa.Column('community_participation', sa.Float(), nullable=True),
    sa.Column('technical_consistency', sa.Float(), nullable=True),
    sa.Column('open_source_contributions', sa.Float(), nullable=True),
    sa.Column('hackathon_performance', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('renormalized_subscores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_available_signals', sa.Integer(), nullable=True),
    sa.Column('confidence_expected_signals', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('score_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scores_candidate_time', 'talent_scores', ['candidate_id', 'computed_at'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fraud_flag_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('candidate_statement', sa.Text(), nullable=True),
    sa.Column('supporting_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_assist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['fraud_flag_id'], ['fraud_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disputes_flag', 'disputes', ['fraud_flag_id'], unique=False)
    op.create_table('hackathon_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'team_id', name='uq_hackathon_rankings_hackathon_team')
    )
    op.create_index('idx_hackathon_rankings_hackathon_rank', 'hackathon_rankings', ['hackathon_id', 'rank'], unique=False)
    op.create_index('idx_hackathon_rankings_team', 'hackathon_rankings', ['team_id'], unique=False)
    op.create_table('hackathon_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.CheckConstraint("role IN ('lead','member')", name='ck_hackathon_team_members_role'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'candidate_id', name='uq_hackathon_team_members_team_candidate')
    )
    op.create_index('idx_hackathon_team_members_candidate', 'hackathon_team_members', ['candidate_id'], unique=False)
    op.create_index('idx_hackathon_team_members_team', 'hackathon_team_members', ['team_id'], unique=False)
    op.create_table('interview_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('response_confidence_signal', sa.Float(), nullable=True),
    sa.Column('technical_rating', sa.Float(), nullable=True),
    sa.Column('communication_rating', sa.Float(), nullable=True),
    sa.Column('rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hiring_recommendation', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_reports_session', 'interview_reports', ['session_id'], unique=False)
    op.create_table('interview_transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('agent','candidate')", name='ck_interview_transcripts_role'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_transcripts_session_turn', 'interview_transcripts', ['session_id', 'turn_index'], unique=False)
    op.create_table('plagiarism_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('matched_presentation_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_presentation_id'], ['presentations.id'], ),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plagiarism_matches_presentation', 'plagiarism_matches', ['presentation_id'], unique=False)
    op.create_table('presentation_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('innovation_score', sa.Float(), nullable=True),
    sa.Column('technical_feasibility_score', sa.Float(), nullable=True),
    sa.Column('presentation_quality_score', sa.Float(), nullable=True),
    sa.Column('business_potential_score', sa.Float(), nullable=True),
    sa.Column('overall_pitch_score', sa.Float(), nullable=True),
    sa.Column('renormalized_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_content_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_presentation_scores_presentation_time', 'presentation_scores', ['presentation_id', 'computed_at'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_image', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slides_presentation_index', 'slides', ['presentation_id', 'slide_index'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('code_or_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('static_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grading_status', sa.Text(), server_default='done', nullable=False),
    sa.Column('grading_error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submissions_assessment', 'submissions', ['assessment_id'], unique=False)
    op.create_index('idx_submissions_candidate', 'submissions', ['candidate_id'], unique=False)
    op.create_table('hackathon_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('presentation_id', sa.UUID(), nullable=True),
    sa.Column('repo_analysis_submission_id', sa.UUID(), nullable=True),
    sa.Column('judge_score', sa.Float(), nullable=True),
    sa.Column('judge_rationale', sa.Text(), nullable=True),
    sa.Column('judge_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judge_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.ForeignKeyConstraint(['repo_analysis_submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', name='uq_hackathon_submissions_team')
    )
    op.create_index('idx_hackathon_submissions_team', 'hackathon_submissions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hackathon_submissions_team', table_name='hackathon_submissions')
    op.drop_table('hackathon_submissions')
    op.drop_index('idx_submissions_candidate', table_name='submissions')
    op.drop_index('idx_submissions_assessment', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('idx_slides_presentation_index', table_name='slides')
    op.drop_table('slides')
    op.drop_index('idx_presentation_scores_presentation_time', table_name='presentation_scores')
    op.drop_table('presentation_scores')
    op.drop_index('idx_plagiarism_matches_presentation', table_name='plagiarism_matches')
    op.drop_table('plagiarism_matches')
    op.drop_index('idx_interview_transcripts_session_turn', table_name='interview_transcripts')
    op.drop_table('interview_transcripts')
    op.drop_index('idx_interview_reports_session', table_name='interview_reports')
    op.drop_table('interview_reports')
    op.drop_index('idx_hackathon_team_members_team', table_name='hackathon_team_members')
    op.drop_index('idx_hackathon_team_members_candidate', table_name='hackathon_team_members')
    op.drop_table('hackathon_team_members')
    op.drop_index('idx_hackathon_rankings_team', table_name='hackathon_rankings')
    op.drop_index('idx_hackathon_rankings_hackathon_rank', table_name='hackathon_rankings')
    op.drop_table('hackathon_rankings')
    op.drop_index('idx_disputes_flag', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('idx_scores_candidate_time', table_name='talent_scores')
    op.drop_table('talent_scores')
    op.drop_table('presentations')
    op.drop_index('idx_match_scores_job_time', table_name='match_scores')
    op.drop_index('idx_match_scores_job_percentage', table_name='match_scores')
    op.drop_index('idx_match_scores_candidate_id', table_name='match_scores')
    op.drop_table('match_scores')
    op.drop_index('idx_interview_sessions_job_id', table_name='interview_sessions')
    op.drop_index('idx_interview_sessions_definition', table_name='interview_sessions')
    op.drop_index('idx_interview_sessions_candidate_id', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('idx_hackathon_teams_hackathon', table_name='hackathon_teams')
    op.drop_table('hackathon_teams')
    op.drop_index('idx_github_snapshots_candidate', table_name='github_snapshots')
    op.drop_table('github_snapshots')
    op.drop_index('idx_generated_documents_candidate_time', table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index('idx_fraud_flags_subject', table_name='fraud_flags')
    op.drop_index('idx_fraud_flags_status', table_name='fraud_flags')
    op.drop_index('idx_fraud_flags_candidate', table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index('idx_contribution_reports_repo', table_name='contribution_reports')
    op.drop_index('idx_contribution_reports_candidate_id', table_name='contribution_reports')
    op.drop_table('contribution_reports')
    op.drop_index('idx_certifications_candidate_id', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('idx_career_recs_candidate_time', table_name='career_recommendations')
    op.drop_table('career_recommendations')
    op.drop_index('idx_badges_candidate', table_name='badges')
    op.drop_table('badges')
    op.drop_index('idx_authenticity_scores_candidate_time', table_name='authenticity_scores')
    op.drop_table('authenticity_scores')
    op.drop_index('idx_assessments_candidate', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('idx_applications_job_stage', table_name='applications')
    op.drop_index('idx_applications_candidate', table_name='applications')
    op.drop_table('applications')
    op.drop_table('trusted_issuers')
    op.drop_index('idx_recruiter_watchlists_recruiter', table_name='recruiter_watchlists')
    op.drop_table('recruiter_watchlists')
    op.drop_index('idx_jobs_posted_by_user_id', table_name='jobs')
    op.drop_index('idx_jobs_organization_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_interview_definitions_created_by', table_name='interview_definitions')
    op.drop_table('interview_definitions')
    op.drop_table('hackathons')
    op.drop_index('idx_files_owner_type_uploaded', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_copilot_conversations_recruiter_id', table_name='copilot_conversations')
    op.drop_table('copilot_conversations')
    op.drop_table('candidate_profiles')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('idx_fraud_detection_configs_org', table_name='fraud_detection_configs')
    op.drop_table('fraud_detection_configs')
    op.drop_index('idx_verification_records_subject', table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_table('skill_taxonomy')
    op.drop_table('organizations')
    op.drop_table('location_aliases')
    op.drop_index('idx_events_unprocessed_type', table_name='events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('events')
    op.drop_table('course_catalog')
    op.drop_index('idx_agent_runs_subject', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
